import Head from "next/head";
import Image from "next/image";

const ThankYou: React.FC = () => {
  return (
    <>
      <Head>
        <title>Thank You | Interest Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center">
        <div className="bg-white p-10 rounded-lg shadow-lg">
          <div className='flex flex-col items-center justify-end'>
            <Image
              src="/logo.png"
              alt="Map showing service region of Downtown Oakland."
              width={200}
              height={100}
            />
            <h1 className="text-4xl font-heading text-primary mb-4 text-center">Thank You!</h1>
          </div>
          <p className="text-center">
            Your interest form has been submitted successfully. We will be in touch shortly regarding next steps!
          </p>
        </div>
      </main>
    </>
  );
};

export default ThankYou;
